version: '3.9'

services:
  lp-msroot:
      build:
        context: ./services/frontend/lp-msroot
        dockerfile: ../../../docker/Dockerfile.lp-msroot
      container_name: lp-msroot
      ports:
        - "${LP_MSROOT_EXPOSE_PORT}:80"
      networks:
        - microservices-network
      depends_on:
        - user-service
        - product-service
        - order-service

networks:
  microservices-network:
    driver: bridge