FROM node:lts-alpine AS build
WORKDIR /app

COPY services/frontend/lp-msroot/package*.json ./
RUN npm install

COPY services/frontend/lp-msroot/ ./
RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/msroot.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]